### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by MircoCagni** [hvqzao/liffy#4]
First try:
$python liffy.py 
Traceback (most recent call last):
  File "liffy.py", line 11, in <module>
    import core
  File "/home/mirco/Desktop/DedSec/liffy/core.py", line 4, in <module>
    from blessings import Terminal
ImportError: No module named blessings

In second try i have use python3
$python3 liffy.py 
Traceback (most recent call last):
  File "liffy.py", line 8, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by vdvcoder** [comment]
Liffy requires the following libraries: requests, argparse, blessings, urlparse, daemon

Install: pip install {LIBRARIES}

**Comment by Sydwicked** [comment]
urlparse module does not available
